name: Deploy to Heroku

on:
  push:
    branches:
      - main   # atau main, sesuaikan dengan branch utama Anda

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'   # atau versi PHP yang Anda pakai

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "thriftlife"   # ganti dengan nama app Heroku Anda
          heroku_email: "aditanaufal@students.amikom.ac.id"    # ganti dengan email Heroku Anda